apiVersion: batch/v1
kind: Job
metadata:
  name: app-job-rsync
spec:
  template:
    spec:
      volumes:
      - name: data-input
        gcePersistentDisk:
          pdName: glow-data-disk-200
          fsType: ext4
      containers:
      - name: init
        image: google/cloud-sdk:275.0.0-alpine
        command: ["/bin/sh", "-c", "gsutil -m rsync -dr gs://glow-sportradar/ /data/input"]
        volumeMounts:
        - name: data-input
          mountPath: /data/input
      restartPolicy: Never
      backoffLimit: 0

# Create Job with apiVersion "batch/v1" and name is app-job-rsync. Must be volumes section with name "data-input" and mounts a Google Compute Engine persistent disk with popular Linux filesystem. Named this disk as "glow-data-disk-200". Use image google/cloud-sdk:275.0.0-alpine with name "init" and add some command: first is /bin/sh, second - -c, third - gsutil -m rsync -dr gs://glow-sportradar/ /data/input. Add volume mounts with name "data-input" and path "/data/input. The system should not reboot. Limit of backoff is 0.

