apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  restartPolicy: Never
  containers:
    - name: mycontainer
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: password


# Create pod named "app-secret-env". Use image redis with name mycontainer. Environment Variables are two sections: first named "SECRET_USERNAME", secretkeyref with name "mysecret1" and key "username". Second named "SECRET_PASSWORD", secretkeyref with name "mysecret1" and key "password". And never restarts containers.

# This will create the pod with the specified configuration. The container named "mycontainer" will use the redis image. It will have two environment variables: "SECRET_USERNAME" and "SECRET_PASSWORD". The values for these variables are retrieved from a secret named "mysecret1" using the corresponding keys "username" and "password". The restart policy is set to "Never", meaning the containers won't be restarted automatically.
