apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
  - name: app
    image: gcr.io/devops-project-388318/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 3