apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  volumes:
    - name: html
      emptyDir: {}
  containers:
    - name: 1st
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
    - name: 2nd
      image: debian
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - "while true; do date >> /html/index.html; sleep 1; done"

# Create pod with name "app-multi-containers". Add volumes with name "html" and empty dir. Add two conteiners: first must have name "1st" and used image nginx. Mount volume with name "html" and path /usr/share/nginx/html. Second container is named "2nd" with debian image and mounted volume have name "html" and path /html with few commands /bin/sh and -c. And add an arguments: while true; do date >> /html/index.html; sleep 1; done

# This will create the pod with two containers: "1st" using the Nginx image and "2nd" using the Debian image. The "html" volume is mounted to both containers at different paths, and the second container runs a shell command to append the current date to the /html/index.html file every second.
