apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthy
        port: http
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 0
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    volumeMounts:
    - name: data
      mountPath: "/data"
  volumes:
  - name: data
    hostPath:
      path: "/var/lib/app"

# create pod with metadata's name app-volume. Then use image gcr.io/kuar-demo/kuard-amd64:1 with name app. In livenessProbe use path /healthy and port 8080, it should wait 5 seconds before performing the first probe. Timeout use 1 second and should perform a liveness probe every 10 seconds. After 3 consecutive failed results needed to switch probe status to “Failure”. In readinessProbe use path /ready and port 8080. it should wait 0 seconds before performing the first probe and perform a readiness probe every 2 seconds. After 3 consecutive failed results needed to switch probe status to “Failure” and after 1 consecutive successful results needed to switch probe status to “Success”. Use containerPort 8080, name of port by http. In volumeMounts must be mountPath "/data" and name is "data". In volumes switch name "data" and path "/var/lib/app"

# This will create a pod named "app-volume" with a container named "app". The container will use the specified image gcr.io/kuar-demo/kuard-amd64:1 and expose port 8080 with the name "http".

# The pod includes a liveness probe that performs an HTTP GET request to the path "/healthy" on port 8080. It will wait for 5 seconds before performing the first probe and subsequently perform a liveness probe every 10 seconds. If the probe fails three consecutive times, the pod's status will be set to "Failure".

# Additionally, the pod includes a readiness probe that performs an HTTP GET request to the path "/ready" on port 8080. It will wait for 0 seconds before performing the first probe and subsequently perform a readiness probe every 2 seconds. If the probe fails three consecutive times, the pod's status will be set to "Failure". If the probe succeeds once, the pod's status will be set to "Success".

# The pod also includes a volume mount with the name "data" and mount path "/data". Additionally, it has a volume named "data" with a host path at "/var/lib/app".
