apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bash
            command: ["echo", "Hello world"]
          restartPolicy: OnFailure

# Create CronJob with name "app-cronjob" and apiVersion "batch/v1beta1". String of schedule is "*/5 * * * *". Use image bash with name "hello" and add command ["echo",  "Hello world"]. Add restart policy when system on failure.

