apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: app-container
    image: gcr.io/devops-project-388318/demo:v1.0.0
    ports:
    - name: http
      containerPort: 8080